### ISSUE TITLE
who not PPTP/L2TP?

### ISSUE THREAD

**Issue by cyberghost404** [Kcchouette/OpenVPN-VPS#10]
Hi, why not create a l2tp or pptp with a web muzzle like an Instavpn? It would be very cool :-) These protocols do not lose speed, I use mostly VPN and these 2 very convenient protocols for use

**Comment by Kcchouette** [comment]
> why not create a l2tp or pptp

Because my goal was to publish as open source my script of configuring openVPN, and good hardening.
PPTP is considered as insecure, but some project build a vpn with theses protocols: https://github.com/xebd/accel-ppp / https://github.com/viljoviitanen/setup-simple-pptp-vpn

I don't know your use-case, but you should think to switch to openVPN / wireguard (via https://github.com/StreisandEffect/streisand or https://github.com/trailofbits/algo). Wireguard seems a good compromise when speaking about security and speed
